theme = "dark_plus"

[editor]
line-number = "relative"
mouse = false
cursorline = true
cursorcolumn = true
bufferline = "always"

[editor.soft-wrap]
enable = true

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "position-percentage", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NOR"
mode.insert = "INS"
mode.select = "SEL"

[keys.normal."space"]
o = "file_picker_in_current_buffer_directory"

[editor.lsp]
display-inlay-hints = true
